server:
  port: 8080  # Puerto del Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081  # Dirección del microservicio-product
          predicates:
            - Path=/api/products/**
          filters:
          - StripPrefix=1

        - id: ai-service
          uri: http://localhost:8002  # Dirección del microservicio de IA en FastAPI
          predicates:
            - Path=/api/ia/**
          filters:
            - StripPrefix=2

        - id: auth-service
          uri: http://localhost:8003
          predicates:
          - Path=/api/auth/**
          filters:
          - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}
    config:
      enabled: false